@host = 192.168.0.105
@port = 3000
@URL = http://{{host}}:{{port}}

GET {{URL}}/

###
GET {{URL}}/addEmployee
?name=Ayush-Shashank
&dept=CSE
###
GET {{URL}}/addEmployee
?name=Ayush Shashank
&dept=CS
&bio=Lorem Ipsum

###
GET {{URL}}/adminLogin
?user=root
&pass=root

###
GET {{URL}}/getEmployees

###
GET {{URL}}/getDepartments
###
GET {{URL}}/employeeLogin
?empCode=EMP0050
&encPass=abc

###
GET {{URL}}/updateEmployee
?empCode=EMP0050
&dept=CS
&bio=Lorem
&isResetPass=0
&eInTime=9:30
&eOutTime=16:00
&startDate=2021-06-10
###
GET {{URL}}/deleteEmployee
?empCode=EMP0030

###
GET {{URL}}/markEmployeeAttendance
?empCode=EMP0036

###
GET {{URL}}/getEmployeeAttendance
?empCode=EMP0037
&month=6
&year=2021

###
GET {{URL}}/markEmployeeCheckin
?empCode=EMP0037

###
GET {{URL}}/markEmployeeCheckout
?empCode=EMP0037