@host = 192.168.0.105
@port = 3000
@URL = http://{{host}}:{{port}}

GET {{URL}}/

###
GET {{URL}}/addEmployee
?name=Ayush-Shashank
&dept=CSE
###
GET {{URL}}/addEmployee
?name=Ayush Shashank
&dept=CS
&bio=Lorem Ipsum

###
GET {{URL}}/adminLogin
?user=root
&pass=root

###
GET {{URL}}/getEmployees

###
GET {{URL}}/employeeLogin
?empCode=EMP0028
&encPass=abc

###
GET {{URL}}/updateEmployee
?empCode=EMP0029
&dept=IS
&bio=Lorem
&isResetPass=1

###
GET {{URL}}/deleteEmployee
?empCode=EMP0029
&dept=IS
&bio=Lorem
&isResetPass=1

###
GET {{URL}}/markEmployeeAttendance
?empCode=EMP0031

###
GET {{URL}}/getEmployeeAttendance
?empCode=EMP0031
&month=5
&year=2021

###
GET {{URL}}/markEmployeeCheckin
?empCode=EMP0031

###
GET {{URL}}/markEmployeeCheckout
?empCode=EMP0031